name: AmpleChatBot
main: org.jaggy.bukkit.ample.Ample
version: 1.2.8
author: matthewl6970, licks92
softdepend: [Essentials]
commands:
 answer:
  description: Sets the response to Question ID.
  usage: /<command> <QID> <answer>
  aliases: [ampa, aa]
 question:
  description: Adds question or key phrase.
  usage: /<command> <question or key phrase>
  aliases: [ampq, aq]
 qlist:
  description: lists question or key phrase.
  usage: /<command> [QID][question][keyphrase]
  aliases: [ampl, al]
 delquestion:
  description: deletes questions or key phrases.
  usage: /<command> <QID>
  aliases: [ampd, ad]
 ample:
  description: Displays the help for the Ample plugin.
  usage: /<command>
permissions:
 ample.invoke:
  description: Allows people to invoke responses.
 ample.edit:
  description: Allows to editing/adding of questions and answers.
 ample.qlist:
  description: Allows to view the list of questions.
 ample.delete:
  description: Allows to delete questions.
 ample.allowabuse:
  description: Allows to bypass abuse routines.