name: Ample
main: org.jaggy.bukkit.ample.Ample
version: 1.2.6
author: matthewl6970
commands:
 answer:
  description: Sets the response to Question ID.
  usage: /<command> <QID> <answer>
  alias: [ampa]
 question:
  description: Adds question or key phrase.
  usage: /<command> <question or key phrase>
  alias: [ampq]
 qlist:
  description: lists question or key phrase.
  usage: /<command> [QID][question][keyphrase]
  alias: [ampl]
 delquestion:
  description: deletes questions or key phrases.
  usage: /<command> <QID>
  alias: [ampd]
 ample:
  description: Displays the help for the Ample plugin.
  usage: /<command>
permissions:
 ample.invoke:
  description: Allows people to invoke responses.
 ample.edit:
  description: Allows to editing/adding of questions and answers.
 ample.qlist:
  description: Allows to view the list of questions.
 ample.delete:
  description: Allows to delete questions.